### ISSUE TITLE
Cesium Crashing -- 'Property of 1 not found for undefined' in DrawHelper.js:249

### ISSUE THREAD

**Issue by ianrtracey** [leforthomas/cesium-drawhelper#12]
I am experiencing a halting of rendering for Cesium at seemingly random times due to the following line in DrawHelper.js:

DrawHelper.js:249: lineWidth : Math.min(this.strokeWidth || 4.0, context._aliasedLineWidthRange[1])

I commented out the line and the error appears to have gone away and I don't see any changes reflected in the appearance of Cesium. 

What is this line being used for? I am confused as to why it would be throwing an error that would prompt Cesium to crash.

**Comment by getardretard** [comment]
I too am experiencing this issue. Is there any update?

**Comment by saharki** [comment]
**DrawHelper.js**

Replace line 294 (not 249):
` lineWidth : Math.min(this.strokeWidth || 4.0, context._aliasedLineWidthRange[1])`
with:
` lineWidth : this.strokeWidth || 4.0`  

This change appears here (line 294):
https://github.com/saharki/cesium-drawhelper/blob/master/DrawHelper.js

**Comment by ianrtracey** [comment]
:+1:
